name: "sandbox"
on:
  workflow_dispatch:

jobs:
  sandbox:
    runs-on: ubuntu-latest
    continue-on-error: false
    steps:
      - uses: actions/checkout@v4
      - name: step2
        id: step2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -e
          pwd
          ls -l
          whoami
